"""sync users fields (privacy/admin/premium/morning)

Revision ID: 01286a052106
Revises: 3e6a508adf17
Create Date: 2025-12-10 06:12:02.106535

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "01286a052106"
down_revision: Union[str, Sequence[str], None] = "3e6a508adf17"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
