"""analytics_events id identity

Revision ID: c23cdec84ace
Revises: 5f6f8f49b718
Create Date: 2026-01-13 22:22:30.003239

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'c23cdec84ace'
down_revision: Union[str, Sequence[str], None] = '5f6f8f49b718'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        """
        DO $$
        BEGIN
          IF NOT EXISTS (
            SELECT 1
            FROM information_schema.columns
            WHERE table_name='analytics_events'
              AND column_name='id'
              AND is_identity='YES'
          ) THEN
            EXECUTE 'ALTER TABLE analytics_events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY';
          END IF;
        END $$;
        """
    )


def downgrade() -> None:

    op.execute("""
        ALTER TABLE analytics_events
        ALTER COLUMN id
        DROP IDENTITY IF EXISTS
    """)
